Repository Dori-Room/DoriRoom-BE, pull requests merged in 2025-08, with the labels that each got.

#38 comment: 주석 삭제
  src/main/java/doritos/doriroom/tourApi/dto/response/TourApiDetailInfoDto.java
Labels: 🌏 Deploy

#85 fix: 일기별 리워드 수정 및 응답 DTO에 리워드 추가
  src/main/java/doritos/doriroom/diary/dto/response/DiaryResponseDto.java
  src/main/java/doritos/doriroom/diary/service/DiaryService.java
Labels: ✨ Feature, 📬 API

#86 fix: 인기 축제 조회 쿼리 변경
  src/main/java/doritos/doriroom/event/repository/EventRepositoryImpl.java
Labels: 📬 API, 🔨 Refactor

#95 Feature/76 follow
  src/main/java/doritos/doriroom/follow/controller/FollowController.java
  src/main/java/doritos/doriroom/follow/service/FollowService.java
Labels: 📬 API, 🔨 Refactor
