Repository Dori-Room/DoriRoom-BE, pull requests merged in 2025-09, with the labels that each got.

#117 Feature/73 email based find
  Dockerfile
  src/main/java/doritos/doriroom/auth/common/AuthConstants.java
  src/main/java/doritos/doriroom/auth/controller/AuthController.java
  src/main/java/doritos/doriroom/auth/dto/request/ResetPasswordRequestDto.java
  src/main/java/doritos/doriroom/auth/dto/request/SendPasswordResetCodeRequestDto.java
  src/main/java/doritos/doriroom/auth/dto/request/SignupRequestDto.java
  src/main/java/doritos/doriroom/auth/service/AuthService.java
  src/main/java/doritos/doriroom/auth/template/EmailTemplate.java
  src/main/java/doritos/doriroom/user/exception/UserNotFoundException.java
  src/main/java/doritos/doriroom/user/repository/UserRepository.java
Labels: ✨ Feature, 📬 API

#129 Fix/128 item
  src/main/java/doritos/doriroom/item/service/ItemService.java
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#130 Feat/124 diary
  src/main/java/doritos/doriroom/diary/repository/DiaryRepository.java
  src/main/java/doritos/doriroom/diary/service/DiaryService.java
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#135 feat: 단짝 여부 확인용 API 추가
  src/main/java/doritos/doriroom/follow/controller/FollowController.java
  src/main/java/doritos/doriroom/follow/service/FollowService.java
Labels: ✨ Feature, 📬 API

#149 feat: http로 들어오는 이미지 url을 https로 저장
  src/main/java/doritos/doriroom/event/domain/Event.java
Labels: 🐞 BugFix, 📬 API

#164 Feature/154 fcm
  .gitignore
  src/main/java/doritos/doriroom/challenge/service/ChallengeService.java
  src/main/java/doritos/doriroom/diary/repository/DiaryRepository.java
  src/main/java/doritos/doriroom/diary/service/DiaryLikeService.java
  src/main/java/doritos/doriroom/follow/service/FollowService.java
  src/main/java/doritos/doriroom/global/config/FirebaseConfig.java
  src/main/java/doritos/doriroom/guestbook/service/GuestbookService.java
  src/main/java/doritos/doriroom/notification/NotificationController.java
  src/main/java/doritos/doriroom/notification/domain/Notification.java
  src/main/java/doritos/doriroom/notification/domain/NotificationType.java
  src/main/java/doritos/doriroom/notification/dto/NotificationResponseDto.java
  src/main/java/doritos/doriroom/notification/exception/AccessDeniedException.java
  src/main/java/doritos/doriroom/notification/exception/NotificationNotFoundException.java
  src/main/java/doritos/doriroom/notification/repository/NotificationRepository.java
  src/main/java/doritos/doriroom/notification/service/NotificationService.java
  src/main/java/doritos/doriroom/user/controller/UserController.java
  src/main/java/doritos/doriroom/user/domain/User.java
  src/main/java/doritos/doriroom/user/dto/request/FcmTokenRequestDto.java
  src/main/java/doritos/doriroom/user/service/UserService.java
Labels: ✨ Feature, 📬 API

#162 refactor(challenge): challenge 엔티티가 캐싱되지 않던 문제 해결, dto를 캐싱
  src/main/java/doritos/doriroom/challenge/service/ChallengeService.java
Labels: 🐞 BugFix, 🔨 Refactor
